name: DevOps Team
on: workflow_dispatch
jobs:
  DevOps:
   runs-on: ubuntu-latest
   steps:
     - name: Demo_dev
       run: |
        echo "this is line one"
        echo "this is line two"
        echo "this is line three"
