name: DevOps Team
on: 
 push:
   branches:
    - main
 pull_request:
   types:
    - opened
   branches:
    - main
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Build step
      run: echo "A demo Buld Step"
 test:
   runs-on: ubuntu-latest
   needs: build
   steps:
    - name: Test step
      run: echo "A demo Test Step"
 deploy:
   runs-on: ubuntu-latest
   needs: test
   steps:
   - name: Deploy Step
     run: echo "A demo Deploy Step"
