name: Inputs Demo
on:
  workflow_dispatch: 
    inputs:
      environment:
        description: "choose the environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
         - dev
         - test
         - prod
      artifact_tag:
       description: choose the tag to deploy
       required: true
       type: string
jobs:
 input-demo:
  runs-on: ubuntu-latest
  steps: 
    - name: deployb the app
      run: echo "deploying the ${{ inputs.artifact_tag }} application to ${{ inputs.environment }}"
