name: New input demo
on: 
 workflow_dispatch:
  inputs:
   environment:
    description: "the environment where the application has to deploy"
    default: "dev"
    type: choice
    required: true
    options:
     - dev
     - stage
     - prod 
   artifact_tag: 
    description: the version of tag to deploy
    type: string
jobs:
  input-demo:
   runs-on: ubuntu-latest
   steps:
     - name: deploy tag to stage
       run: echo"deploying tag ${{ inputs.artifact_tag }} to application env ${{ inputs.environment }}"
