name: New input demo
on: 
 workflow_dispatch:
  inputs:
   environment:
    description: deployig to the environment
    default: "dev"
    required: true
    type: choice
    options:
     - dev
     - stage
     - prod
   artifact_tag:
    description: choosing the specific tag
    type: "string"
jobs:
   input-demo:
     runs-on: ubuntu-latest
     steps:
      - name: deploying specific artifact tag to specifc env 
        run: echo deploying the ${{ inputs.artifact_tag }} application to ${{ inputs.environment }}
